### ISSUE TITLE
Error running application handler : undefined symbol

### ISSUE THREAD

**Issue by bmuller95** [Lapin0t/py-swirld#6]
Hi, I have installed python 3.5, pysodium-0.7.0 and bokeh-0.12.16 in a virtualenv but when running the command **bokeh serve --show viz.py --args 5** 
we have this error

2018-05-17 14:18:10,798 Starting Bokeh server version 0.12.16 (running on Tornado 5.0.2)
2018-05-17 14:18:10,801 Bokeh app running at: http://localhost:5006/viz
2018-05-17 14:18:10,802 Starting Bokeh server with process id: 25551
2018-05-17 14:18:11,026 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7fb2f1b49cc0>: /usr/lib/x86_64-linux-gnu/libsodium.so.18: undefined symbol: crypto_pwhash_bytes_max
File "__init__.py", line 365, in __getitem__:
func = self._FuncPtr((name_or_ordinal, self)) Traceback (most recent call last):
  File "/users/promo2019/bmuller/env/lib/python3.5/site-packages/bokeh/application/handlers/code_runner.py", line 163, in run
    exec(self._code, module.__dict__)
  File "/users/promo2019/bmuller/hashgraph/py-swirld/viz.py", line 16, in <module>
    from pysodium import crypto_sign_keypair
  File "/users/promo2019/bmuller/env/lib/python3.5/site-packages/pysodium/__init__.py", line 156, in <module>
    sodium.crypto_pwhash_bytes_max.restype=ctypes.c_uint
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libsodium.so.18: undefined symbol: crypto_pwhash_bytes_max
 
2018-05-17 14:18:11,039 200 GET /viz (::1) 87.51ms
2018-05-17 14:18:11,276 101 GET /viz/ws?bokeh-protocol-version=1.0&bokeh-session-id=jl0A5x5bnRy1KmTUkJSA7eCpLaZJyFp7CJTIrPtvNol8 (::1) 0.62ms
2018-05-17 14:18:11,276 WebSocket connection opened
2018-05-17 14:18:11,277 ServerConnection created

![capture du 2018-05-17 14-34-12](https://user-images.githubusercontent.com/33894325/40180363-ed8349fc-59e6-11e8-8425-21d134273523.png)

Do you have any idea what could be done to fix this ? Thank you

**Comment by Lapin0t** [comment]
Seems to be smthg with your version of libsodium.. long time since i didn't look at this code but right now i've got libsodium 1.0.16. Could you try to upgrade it? (your system package and also pysodium) Check out if the pysodium doc talks about supported libsodium version too.

**Comment by bmuller95** [comment]
Thank you ! It really helped :)
